#!/bin/bash

PORT=4002

function serve {
	echo "serving public folder"
	echo "listening at port $PORT"
	
	while true;
	do
		if ! nc -c './hacky serve-one' -l -p $PORT; then
			# CTRL+C: exit
			exit
		fi
	done;
}

serve
